FROM node:22-alpine

# Set node to run as production
ENV NODE_ENV production

# Set working directory
WORKDIR /app

# Copy application files
COPY node .
COPY js .

# Install dependencies
RUN npm i

# Expose game server port
EXPOSE 8082

CMD ["node", "server.js", "EU", "I", "8082"]